### ISSUE TITLE
"O tpEmis {ide.tpEmis} não é suportado."

### ISSUE THREAD

**Issue by willianflopes** [SilverCard/DanfeSharp#17]
O método CreateFromXml(ProcNFe procNfe) da classe DanfeViewModelCreators contém a linha:

```
if (FormasEmissaoSuportadas.Contains(model.TipoEmissao))
{
throw new NotSupportedException($"O tpEmis {ide.tpEmis} não é suportado.");
}
```

Quando a emissão é normal e está dentro do tipo de emissão suportada ele lança a exceção acima.
A linha do if não teria de ser a abaixo?

`if (!FormasEmissaoSuportadas.Contains(model.TipoEmissao)) //observe o ! negando o if`

**Comment by SilverCard** [comment]
Teria.

Realmente é um erro de digitação, a intenção é verificar os formatos suportados.

Vou fazer um novo commit em breve, Obrigado :)
________________________________

**Comment by SilverCard** [comment]
Corrigido em 01e2117b38193fc8f97599c5f0e08cb97bd0d9a9, mais um vez obrigado.

**Comment by willianflopes** [comment]
Eu que agradeço por você fornecer o código! Muito obrigado pela disposição! Excelente trabalho.
