### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by thiagomaia971** [SilverCard/DanfeSharp#2]
Foi publicado a ultima versão no Nuget Package?
Estou com a versão 1.0.3 e não encontro a classe ```DanfeViewModelCreator```

**Comment by SilverCard** [comment]
O DanfeSharp não foi publicado no NuGet.

Eu sugiro que use a última versão, 2.0.1, que está no branch "dev".

**Comment by thiagomaia971** [comment]
Baixei e dá dando erro de referencia no PDFClown

**Comment by felixsevero** [comment]
Bom dia, eu utilizo a algum tempo o DanfeSharp por ele ser ótimo na geração do DANFe. Eu gostaria de sugerir que, se possível, ele fosse disponibilizado no Nuget, pois isso facilitaria em muito a adição e atualização da biblioteca. Isso, aliado ao Semantic Versioning (https://semver.org/), tornaria a biblioteca mais confiável para o seu desenvolvimento e utilização.
 Obrigado :)

**Comment by SilverCard** [comment]
Olá, @felixsevero.

O DanfeSharp depende do PDFClown, que infelizmente não é disponibilizado no NuGet pelo autor, e como eu não quero o distribuir, preferi não colocar o DanfeSharp no NuGet.
