### ISSUE TITLE
Nfe 4.00 com erro

### ISSUE THREAD

**Issue by ajacobino** [SilverCard/DanfeSharp#21]
Tentei utilizar o componente para a nfe 4.0 e apresentou o seguinte erro:
![Erro](https://user-images.githubusercontent.com/36011068/54372739-bd649f80-465a-11e9-8c67-7ed4e66a545e.png)
aqui esta o xml:
<?xml version="1.0" encoding="ISO-8859-1"?><nfeProc versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe versao="4.00" Id="NFe35181261610515000106550010002334251002334250"><ide><cUF>35</cUF><cNF>00233425</cNF><natOp>VENDA DE PRODUTOS</natOp><mod>55</mod><serie>1</serie><nNF>233425</nNF><dhEmi>2018-12-22T16:37:05+03:00</dhEmi><tpNF>1</tpNF><idDest>1</idDest><cMunFG>3513801</cMunFG><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>0</cDV><tpAmb>1</tpAmb><finNFe>1</finNFe><indFinal>0</indFinal><indPres>9</indPres><procEmi>0</procEmi><verProc>1.0.0.0</verProc></ide><emit><CNPJ>61610515000106</CNPJ><xNome>LIPSON COSMETICOS LTDA</xNome><xFant>LIPSON COSMETICOS LTDA</xFant><enderEmit><xLgr>RUA INCO</xLgr><nro>210</nro><xBairro>JD. ALBA</xBairro><cMun>3513801</cMun><xMun>DIADEMA</xMun><UF>SP</UF><CEP>09961370</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>1140616435</fone></enderEmit><IE>286135277110</IE><CRT>3</CRT></emit><dest><CNPJ>07278350000163</CNPJ><xNome>SS COM.DE COSM.E PRODUTOS DE HIG.PESSOAL LTDA</xNome><enderDest><xLgr>AV.DAS COMUNICACOES</xLgr><nro>927</nro><xCpl>GALP.IND.PAV.B 4</xCpl><xBairro>INDUSTRIAL ANHANGUERA</xBairro><cMun>3534401</cMun><xMun>OSASCO</xMun><UF>SP</UF><CEP>06276906</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>1136979267</fone></enderDest><indIEDest>1</indIEDest><IE>492515600113</IE></dest><entrega><CNPJ>07278350000163</CNPJ><xLgr>VIA ANHANGUERA</xLgr><nro>KM</nro><xCpl>19 LADO ESQUERDO CAP/INT.PAVIL</xCpl><xBairro>VILA JARAGUA</xBairro><cMun>3534401</cMun><xMun>OSASCO</xMun><UF>SP</UF></entrega><det nItem="1"><prod><cProd>040408</cProd><cEAN>7899601713883</cEAN><xProd>11203-COLONIA DESOD.SPLASH JEQUITI VIDA+RELAX LAVANDA 250ML - Lote-Validade-Qtd:(83551LP-2021/12/20-1105)</xProd><NCM>33072010</NCM><CEST>2801600</CEST><CFOP>5101</CFOP><uCom>UN</uCom><qCom>1105.0000</qCom><vUnCom>5.6800000000</vUnCom><vProd>6276.40</vProd><cEANTrib>7899601713883</cEANTrib><uTrib>UN</uTrib><qTrib>1105.0000</qTrib><vUnTrib>5.6800000000</vUnTrib><indTot>1</indTot><xPed>11203</xPed><nItemPed>149893</nItemPed><rastro><nLote>83551LP</nLote><qLote>1105.000</qLote><dFab>2018-12-20</dFab><dVal>2021-12-20</dVal></rastro></prod><imposto><ICMS><ICMS20><orig>0</orig><CST>20</CST><modBC>3</modBC><pRedBC>33.33</pRedBC><vBC>4184.47</vBC><pICMS>18.00</pICMS><vICMS>753.20</vICMS></ICMS20></ICMS><IPI><cEnq>999</cEnq><IPITrib><CST>50</CST><vBC>6276.40</vBC><pIPI>7.00</pIPI><vIPI>439.34</vIPI></IPITrib></IPI><PIS><PISAliq><CST>02</CST><vBC>6276.40</vBC><pPIS>2.20</pPIS><vPIS>138.08</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>02</CST><vBC>6276.40</vBC><pCOFINS>10.30</pCOFINS><vCOFINS>646.47</vCOFINS></COFINSAliq></COFINS></imposto><infAdProd>;149893</infAdProd></det><total><ICMSTot><vBC>4184.47</vBC><vICMS>753.20</vICMS><vICMSDeson>0.00</vICMSDeson><vFCP>0.00</vFCP><vBCST>0.00</vBCST><vST>0.00</vST><vFCPST>0.00</vFCPST><vFCPSTRet>0.00</vFCPSTRet><vProd>6276.40</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>439.34</vIPI><vIPIDevol>0.00</vIPIDevol><vPIS>138.08</vPIS><vCOFINS>646.47</vCOFINS><vOutro>0.00</vOutro><vNF>6715.74</vNF></ICMSTot></total><transp><modFrete>1</modFrete><transporta><CNPJ>10730615000127</CNPJ><xNome>FAMILY FIGUEIREDO E CUNHA LTDA -ME</xNome><IE>635594028112</IE><xEnder>RUA: PEDRO DA CRUZ SALGADO,87</xEnder><xMun>SAO BERNARDO DO CAMPO</xMun><UF>SP</UF></transporta><vol><qVol>66</qVol><esp>CAIXA(S)</esp><pesoL>0.000</pesoL><pesoB>0.000</pesoB></vol></transp><cobr><fat><nFat>233425</nFat><vOrig>6715.74</vOrig><vDesc>0.00</vDesc><vLiq>6715.74</vLiq></fat><dup><nDup>001</nDup><dVenc>2019-01-05</dVenc><vDup>6715.74</vDup></dup></cobr><pag><detPag><indPag>1</indPag><tPag>15</tPag><vPag>6715.74</vPag></detPag></pag><infAdic><infCpl>Pedido Cliente: 149893; EndereÃ§o de Entrega = VIA ANHANGUERA, KM 19 LADO ESQUERDO CAP/INT.PAVILHAO B(A) - OSASCO - SP; CONDIÃÃO DE SUBSTITUTO TRIBUTARIO ATRIBUIDA AO DESTINATARIO POR REGIME ESPECIAL - PROCESSO ELETRONICO N. 009310/2016 - PIS TRIBUTADO EM 2,20% CONF.LEI FED.10833 DE 29/12/03; COFINS TRIBUTADO EM 10,30% CONF.LEI FED.10833 DE 29/12/03; ICMS:BASE DE CALCULO REDUZIDA CONFORME ANEXO II ARTIGO 34 DO RICMS</infCpl></infAdic></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI="#NFe35181261610515000106550010002334251002334250"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>/tOugovu32QnuY/sC7Vlor6XBGw=</DigestValue></Reference></SignedInfo><SignatureValue>W1Uqf2gp/SAbphkOLzjVgGJT2CIVsvknYa7x7fc3L3A2a+BmZT1v5EMCh87REZfJoXjucM08Si7ZOQzMiCcqv1HxKYp8f3dESutcPGlQLdtBrMy6EIYZm/9uMplADVSj9XefrJhZ3vk64t+v/cL4c+OGlrJhVoB7R6QeVGDgL9D2RAWrMBERYHJ2aebxnJDeUxYV3w/hQDjpazQ61Lh1UMXULaiyHIDXIrQqpcPX4oXb3xXpocLLJpxSAUFbGXmC+BvS9E/Gi+Kue+ooeJddZjfCIFPkXGLjV5sKm8ZQ+Bv+GBggkpfxiHotOPkEF4dGxwoMbWdIRDvUdoB7qfx+uA==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIHuzCCBaOgAwIBAgIQegbkiwjhbt1lZNYh2gQirTANBgkqhkiG9w0BAQsFADB0MQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDEtMCsGA1UECxMkQ2VydGlzaWduIENlcnRpZmljYWRvcmEgRGlnaXRhbCBTLkEuMSEwHwYDVQQDExhBQyBDZXJ0aXNpZ24gTXVsdGlwbGEgRzcwHhcNMTgwNTE2MTMzNjM5WhcNMTkwNTE2MTMzNjM5WjCBhTELMAkGA1UEBhMCQlIxEzARBgNVBAoMCklDUC1CcmFzaWwxIzAhBgNVBAsMGkF1dGVudGljYWRvIHBvciBBUiBSZW5hc2NlMRswGQYDVQQLDBJBc3NpbmF0dXJhIFRpcG8gQTExHzAdBgNVBAMMFkxJUFNPTiBDT1NNRVRJQ09TIExUREEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDime7NCtrS9sYgwR1RIUx0bZDU7ulovfi4cGZUtxwToeasl1beUHx4gYt5e1xCCyzC/NO05WFKTMA1dYZ3mq9kxuyV11rDJN9xMuRVEGLoGRGiWyMNDkcFbXNZLWHV7zygMB/PuhvjfppTDfdCGUDKhGj61o4yx8UawN6DVjbibq1NtVp37RxftdieUnMcQDrwHwLXHraptG1ng9HD9sxSJB46n3x4qk4bcpn8gAqbCR0ZcAyh6U57pegeagD3RXQTv2QYR/9fwNJ4oN/Dr1OdX6iGktUHSo+tLp+Un3muxfEwOLkgKDm835GBqz3wPy2IZwXeVENz0HczbbJ233CVAgMBAAGjggM1MIIDMTCBwwYDVR0RBIG7MIG4oD0GBWBMAQMEoDQEMjIzMDIxOTQ2MDQzMjE2NTA4ODcwMDAwMDAwMDAwMDAwMDAwMDAzMzIwNzIxNVNTUFNQoCYGBWBMAQMCoB0EG0FMRVNTSU8gREUgVE9MRURPIFJPRFJJR1VFU6AZBgVgTAEDA6AQBA42MTYxMDUxNTAwMDEwNqAXBgVgTAEDB6AOBAwwMDAwMDAwMDAwMDCBG2thcmluYV90b2xlZG9AbGlwc29uLmNvbS5icjAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFF1yDL8z0rvjhqboTAZxflVcB6DWMIGLBgNVHSAEgYMwgYAwfgYGYEwBAgELMHQwcgYIKwYBBQUHAgEWZmh0dHA6Ly9pY3AtYnJhc2lsLmNlcnRpc2lnbi5jb20uYnIvcmVwb3NpdG9yaW8vZHBjL0FDX0NlcnRpc2lnbl9NdWx0aXBsYS9EUENfQUNfQ2VydGlTaWduX011bHRpcGxhLnBkZjCBxgYDVR0fBIG+MIG7MFygWqBYhlZodHRwOi8vaWNwLWJyYXNpbC5jZXJ0aXNpZ24uY29tLmJyL3JlcG9zaXRvcmlvL2xjci9BQ0NlcnRpc2lnbk11bHRpcGxhRzcvTGF0ZXN0Q1JMLmNybDBboFmgV4ZVaHR0cDovL2ljcC1icmFzaWwub3V0cmFsY3IuY29tLmJyL3JlcG9zaXRvcmlvL2xjci9BQ0NlcnRpc2lnbk11bHRpcGxhRzcvTGF0ZXN0Q1JMLmNybDAOBgNVHQ8BAf8EBAMCBeAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMIG2BggrBgEFBQcBAQSBqTCBpjBkBggrBgEFBQcwAoZYaHR0cDovL2ljcC1icmFzaWwuY2VydGlzaWduLmNvbS5ici9yZXBvc2l0b3Jpby9jZXJ0aWZpY2Fkb3MvQUNfQ2VydGlzaWduX011bHRpcGxhX0c3LnA3YzA+BggrBgEFBQcwAYYyaHR0cDovL29jc3AtYWMtY2VydGlzaWduLW11bHRpcGxhLmNlcnRpc2lnbi5jb20uYnIwDQYJKoZIhvcNAQELBQADggIBAL7j7tK9X0NC/gJORMEGGy4w+V+MFXPT4zRhWBKNVs2+u4//bg9qXxqd0Gh22M4PwPBbSmmkKVsSuFk4Zay764nuDbaeap6rvrjuCwgOClqyGCZMwihPe89S2eTpvbR2PSI1CP/FM3MtV+Qe+LcIJ5lrt8YMYhT/FMKOu26MgnNsTkgHpVm/9ly4ghtovSMovLYN5y+WwhXYvvPvCoi5fHEy+3WbiWwnzkuZCY0yKlFT6Ur055uEo/er8NzJfjJLLUfof2UpbgTfCaGDi2tVTr2vLrl37WSCJ+28+kg/rEckvS923IjICMbukeEf5/CpxF4NQXq8PGazffCpE48WwOT3a0nVa5kByYAqxhmI+5xWvOxGcHMcKuQtKRBBdNaNEeK0V4od3G7wLHcKi+1JdpPZJ+VnFEpqkaBMZcpEsyvcFgGwo7beYJcpjF+Irj/71uPclpkaZ3iNjKW240MYnhn7Q7gHLxKIgT4m5ej6FuWxUjK5uWwAxRt5tR6RmVmKbt/S47BnbZql7qZ+9Re5hYOdpoP/AlPGJ9zgioIVosCkcqb0Wj2cN6ozsVpOxMAftabEBNVIZfC3VoFPrMV3+CxZa+mbBbpwHt9A5QYNl+wCbTrsB2+zHT+/73lbRFTfJEXbZW4nCXNYE1uURVlvPCjc0eKK8a+bdqEX14n9nrXs</X509Certificate></X509Data></KeyInfo></Signature></NFe><protNFe versao="4.00"><infProt Id="Id135180895960031"><tpAmb>1</tpAmb><verAplic>SP_NFE_PL009_V4</verAplic><chNFe>35181261610515000106550010002334251002334250</chNFe><dhRecbto>2018-12-22T16:55:27-02:00</dhRecbto><nProt>135180895960031</nProt><digVal>/tOugovu32QnuY/sC7Vlor6XBGw=</digVal><cStat>100</cStat><xMotivo>Autorizado o uso da NF-e</xMotivo></infProt></protNFe></nfeProc>

**Comment by felixsevero** [comment]
Tente colocar o XML com as tags para podermos reproduzir.

**Comment by ajacobino** [comment]
Difícil é conseguir ele não deixa eu colocar de jeito nenhum se copio aqui na mensagem ele sai conforme acima, não faz o upload do mesmo, coloquei no drive https://drive.google.com/open?id=1XgTvSJPZFa5DQ-bd9vZ2tnSHQTl0bwM4
caso não consiga me avise que envio por e-mail.

**Comment by SilverCard** [comment]
Isso acontece quando o ShowText do PDF Clown é chamado com uma String contendo caracteres inválidos.
