### ISSUE TITLE
Dúvida Danfe tags <xProd> <infAdProd>

### ISSUE THREAD

**Issue by danilorch** [SilverCard/DanfeSharp#24]
@SilverCard Existe algum tipo de modelo obrigatório para a Descrição dos produtos no DANFE ? ou isso fica a livre critério do usuário, penso em adicionar a informação da imagem abaixo porem tenho receio que fique fora de algum padrão pré estabelecido.

![image](https://user-images.githubusercontent.com/52005910/68880334-d346ca80-06e9-11ea-9baf-4242c034d093.png)

**Comment by SilverCard** [comment]
Olá, @Dan504.

Eu não sei te dizer ao certo, porém recomendo que consulte o Manual de Orientação do Contribuinte para sanar essa dúvida.

**Comment by danilorch** [comment]
Obrigado @SilverCard, Forte abraço.
