### ISSUE TITLE
NFe 4.00

### ISSUE THREAD

**Issue by claubercy** [SilverCard/DanfeSharp#6]
Boa noite.

Vocês tem planejamento de liberar a dll para imprimir Danfe de NFe versão 4.00?

**Comment by SilverCard** [comment]
Olá,

O DanfeSharp já consegue gerar DANFEs da NFe v4.00.

Por enquanto essa biblioteca é destinada apenas a desenvolvedores, por isso está disponível apenas em código fonte, e não em DLL.

**Comment by claubercy** [comment]
Eu sou desenvolvedor. Tem como disponibilizar o código fonte?

**Comment by ulissescappato** [comment]
Boa tarde!

Tentei imprimir uma nota recebida por um cliente (versão 4.0), mas deu erro. É referente à modalidade do frete (ModFrete). O valor é 3 e parece que não está sendo tratado...

Há alguma previsão para liberação da versão final?

Obrigado e parabéns pelo trabalho.

**Comment by SilverCard** [comment]
Boa tarde, @ulissescappato.

Realmente o modFrete com o valor 3 não está sendo tratado, dentro dos próximos dias eu vou corrigir o problema.

**Comment by SilverCard** [comment]
@ulissescappato 

O problema foi corrigido no commit 559f4903998eadb8f5783216b6d66bf14e62cd11.

**Comment by ulissescappato** [comment]
Obrigado! Grande abraço!

**Comment by fatechbr** [comment]
Olá amigo, gostaria de saber se foi vc que criou esse danfesharp? Sabe pq, eu uso o código fonte dele há anos e fiz várias implementações legais, como por exemplo o extrato do Sat, na hora de imprimir o Danfesharp eu passo um parâmetro junto com o XML.

**Comment by SilverCard** [comment]
Olá, @faironsp.

Eu desenvolvi o DanfeSharp pois não havia outra biblioteca para gerar DANFEs em C#, inicialmente eu o publiquei no finado CodePlex, e agora o projeto está aqui no GitHub.

Fico feliz em saber que ele foi útil =)

**Comment by fatechbr** [comment]
Oi Ricardo, que legal, eu peguei o fonte lá mesmo no CodePlex, não tenho palavras para te agradecer!!!
