### ISSUE TITLE
 .Net Standart 2.0

### ISSUE THREAD

**Issue by scalarerp** [SilverCard/DanfeSharp#8]

**Comment by SilverCard** [comment]
Olá,

Não tenho planos para disponibilizar uma versão do DanfeSharp em .NET Standard, pois ele depende do PDF Clown, que ainda não é disponibilizado oficialmente em .NET Standard.

**Comment by scalarerp** [comment]
Se tu fosse falar em outra DLL para gerar PDF em NetStandart, qual tu recomendaria para trocar esta PDFCLOWN?
Teria interesse em executar um "job" para trocar esta versão?

**Comment by scalarerp** [comment]
Ok, obrigado, já consegui, para quem precisar existe um PDFCLOWN.NETSTANDART, estou utilizando e funciona muito bem.
